### ISSUE TITLE
Annotation tool (sequence & position extraction)

### ISSUE THREAD

**Issue by phegnal** [LangeLab/DataAnalysisPipeline#7]
- fails if multiple protein IDs are present
> only consider first (even better, only consider first starting with Q or P)

- append results to dataframe so they can be used at later steps

**Comment by eneskemalergin** [comment]
I have two potential routes to take for the multiple protein ID/multiple sequences in certain instances:
- Select the first element, as you mentioned above, this would be the **fastest** option
   - I am wondering what type of potential downsides this can cause.
- Explode the multiple elements into their own rows, this is slower and can cause further speed loss since the number of data will be more.

---

Here is some of my changes to the first steps:
1. Open the data
2. Clean the data with already established cleaning steps and handling multiple protein IDs by selecting the first.
3. Append sequence-based annotation using the UniProt 
4. Save the quant data and annotation data as list elements to use in the further steps.

**Comment by phegnal** [comment]
The first (ideally first with PQ) is fine. Exploding comes with its own problems. We might go with a more elaborate approach defining termini groups in the future but this will do for now.
